from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('student', views.student, name='student'),
    path('instructor', views.instructor, name='instructor'),
    path('manager', views.manager, name='manager'),
    path('loginStudent',views.loginStudent,name="loginStudent"),
    path('loginInstructor',views.loginInstructor,name="loginInstructor"),
    path('loginManager',views.loginManager,name="loginManager"),
    path('student/home', views.studentHome, name='studentHome'),
    path('student/listAllCourses', views.listAllCourses, name='listAllCourses'),
    path('student/enrollCourse', views.enrollCourse, name='enrollCourse'),
    path('student/enrollCourseWorker', views.enrollCourseWorker, name='enrollCourseWorker'),
    path('student/listMyCourses', views.listMyCourses, name='listMyCourses'),
    path('student/searchKeyword', views.searchKeyword, name='searchKeyword'),
    path('student/searchKeywordWorker', views.searchKeywordWorker, name='searchKeywordWorker'),
    path('student/filterCourses', views.filterCourses, name='filterCourses'),
    path('student/filterCoursesWorker', views.filterCoursesWorker, name='filterCoursesWorker'),
    path('instructor/home', views.instructorHome, name='instructorHome'),
    path('instructor/listClassrooms', views.listClassrooms, name='listClassrooms'),
    path('instructor/listClassroomsWorker', views.listClassroomsWorker, name='listClassroomsWorker'),
    path('instructor/addCourse', views.addCourse, name='addCourse'),
    path('instructor/addCourseWorker', views.addCourseWorker, name='addCourseWorker'),
    path('instructor/addPrerequisite', views.addPrerequisite, name='addPrerequisite'),
    path('instructor/addPrerequisiteWorker', views.addPrerequisiteWorker, name='addPrerequisiteWorker'),
    path('instructor/viewMyCourses', views.viewMyCourses, name='viewMyCourses'),
    path('instructor/listStudents', views.listStudents, name='listStudents'),
    path('instructor/listStudentsWorker', views.listStudentsWorker, name='listStudentsWorker'),
    path('instructor/changeName', views.changeName, name='changeName'),
    path('instructor/changeNameWorker', views.changeNameWorker, name='changeNameWorker'),
    path('instructor/uploadGrade', views.uploadGrade, name='uploadGrade'),
    path('instructor/uploadGradeWorker', views.uploadGradeWorker, name='uploadGradeWorker'),
    path('manager/home', views.managerHome, name='managerHome'),
    path('manager/addStudent', views.addStudent, name='addStudent'),
    path('manager/addStudentWorker', views.addStudentWorker, name='addStudentWorker'),
    path('manager/addInstructor', views.addInstructor, name='addInstructor'),
    path('manager/addInstructorWorker', views.addInstructorWorker, name='addInstructorWorker'),
    path('manager/deleteStudent', views.deleteStudent, name='deleteStudent'),
    path('manager/deleteStudentWorker', views.deleteStudentWorker, name='deleteStudentWorker'),
    path('manager/updateTitle', views.updateTitle, name='updateTitle'),
    path('manager/updateTitleWorker', views.updateTitleWorker, name='updateTitleWorker'),
    path('manager/viewStudents', views.viewStudents, name='viewStudents'),
    path('manager/viewInstructors', views.viewInstructors, name='viewInstructors'),
    path('manager/viewGrades', views.viewGrades, name='viewGrades'),
    path('manager/viewGradesWorker', views.viewGradesWorker, name='viewGradesWorker'),
    path('manager/viewCourses', views.viewCourses, name='viewCourses'),
    path('manager/viewCoursesWorker', views.viewCoursesWorker, name='viewCoursesWorker'),
    path('manager/viewAverage', views.viewAverage, name='viewAverage'),
    path('manager/viewAverageWorker', views.viewAverageWorker, name='viewAverageWorker'),
]